# Generated by Django 3.0.5 on 2020-04-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200410_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='for_rent_only',
            field=models.BooleanField(default=False),
        ),
    ]
