# Generated by Django 3.0.5 on 2020-04-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20200410_1353'),
        ('listings', '0005_auto_20200414_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='realtors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor'),
        ),
    ]
